-- Inserting data into the department table
INSERT INTO department (d_name) VALUES
    ('Sales'),
    ('Marketing'),
    ('Finance'),
    ('HR'),
    ('Engineering'),
    ('Operations'),
    ('IT'),
    ('Customer Support'),
    ('Research and Development'),
    ('Quality Assurance'),
    ('Human Resources'),
    ('Administration'),
    ('Logistics'),
    ('Public Relations'),
    ('Product Management'),
    ('Legal'),
    ('Design'),
    ('Training'),
    ('Business Development'),
    ('Sales');
    
-- Inserting data into the employee table
INSERT INTO employee (e_name, gender, age, department_id) VALUES
    ('Alice', 'female', 30, 21),
    ('Bob', 'male', 45, 21),
    ('Carol', 'female', 25, 22),
    ('David', 'male', 35, 23),
    ('Eve', 'female', 29, 24),
    ('Frank', 'male', 70, 25),
    ('Grace', 'female', 23, 26),
    ('Henry', 'male', 55, 27),
    ('Ivy', 'female', 42, 28),
    ('Jack', 'male', 88, 29),
    -- Duplicated employee names
    ('John', 'male', 45, 21),
    ('John', 'male', 45, 21),
    ('John', 'male', 45, 22),
    ('John', 'male', 45, 23),
    ('John', 'male', 45, 24),
    ('Jane', 'female', 30, 25),
    ('Jane', 'female', 30, 26),
    ('Jane', 'female', 30, 27),
    ('Jane', 'female', 30, 28),
    ('Jane', 'female', 30, 29),
    -- Add more employee data here...
    ('Samantha', 'female', 42, 30),
    ('Michael', 'male', 55, 31),
    -- Add more employee data here...
    ('John', 'male', 45, 40),
    ('John', 'male', 45, 40),
    ('John', 'male', 45, 40),
    ('John', 'male', 45, 40),
    ('John', 'male', 45, 40),
    ('Jane', 'female', 30, 40),
    ('Jane', 'female', 30, 40),
    ('Jane', 'female', 30, 40),
    ('Jane', 'female', 30, 40),
    ('Jane', 'female', 30, 40);